version: "3.8"
# not tested. Created after merging the two containers
services:
  app:
    image: europe-docker.pkg.dev/mpom-shared/owswims-repo/owswims:latest
    environment:
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASS=${DB_PASS:-your-database-password}
      - DB_HOST=db
    env_file:
      - backend/.env
    depends_on:
      - db
    build:
      context: .
      args:
        - GOOGLE_MAPS_KEY=${GOOGLE_MAPS_API_KEY:-your-google-maps-api-key}
        - GRAPHQL_ENDPOINT=http://localhost:8000/graphql
        - SECRET_KEY=${SECRET_KEY:-your-django-secret-key}
        - DEBUG=True
        - ALLOWED_HOSTS=localhost
        - DB_USER=postgres
        - DB_NAME=postgres
        - DB_PASS=${DB_PASS:-your-database-password}
        - DB_HOST=db
        - GMAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-your-google-maps-api-key}
    ports:
      - "8000:8000"


  db:
    image: postgres
    restart: always
    ports:
      - "25432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS:-your-database-password}
      POSTGRES_USER: postgres

