services:
  app:
    build:
      context: .
      args:
        # only used at build time -> for the frontend
        - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-}
        - RAPIDAPI_KEY=${RAPIDAPI_KEY:-}
        - GRAPHQL_ENDPOINT=
        - DEFAULT_HEADER_PHOTO_URL=${DEFAULT_HEADER_PHOTO_URL:-https://storage.googleapis.com/owswims-prod/photos/default-image.jpg}
        - SECRET_KEY=${SECRET_KEY:-your-django-secret-key}
        - SENTRY_DSN=${SENTRY_DSN:-}
        - RELEASE_ID=local-dev
        - CI_COMMIT_REF_SLUG=local
        - CI_COMMIT_SHA=local
        - CI_BUILD_DATE=local

    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - GS_BUCKET_NAME=${GS_BUCKET_NAME}
      - FRONTEND_URL=${FRONTEND_URL}
      - SPARKPOST_API_KEY=${SPARKPOST_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"

