version: "3.8"
# not tested. Created after merging the two containers
services:
  app:
    image: gcr.io/owswims/app:latest
    depends_on:
      - db
    build:
      context: ./frontend
      args:
        - GOOGLE_MAPS_KEY=AIzaSyBJm1Vv5sZa0ZlRZ4-vxNSQQydMwXDPzZw
        - GRAPHQL_ENDPOINT=http://localhost:8000/graphql
        - SECRET_KEY=dfgim4p02mi2mg2eign2
        - DEBUG=True
        - ALLOWED_HOSTS=localhost
        - DB_USER=postgres
        - DB_NAME=postgres
        - DB_PASS=owswims
        - DB_HOST=db
        - GMAPS_API_KEY=AIzaSyBJm1Vv5sZa0ZlRZ4-vxNSQQydMwXDPzZw
    ports:
      - "8000:8000"


  db:
    image: postgres
    restart: always
    ports:
      - "25432:5432"
    environment:
      POSTGRES_PASSWORD: owswims
      POSTGRES_USER: postgres

